export const ENTITIES = {
  issurMelacha: 'binary_sensor.jewish_calendar_issur_melacha_in_effect',
  motzei: 'binary_sensor.jewish_calendar_motzei_shabbat_hag',
  candleLighting: 'sensor.jewish_calendar_upcoming_candle_lighting',
  havdalah: 'sensor.jewish_calendar_upcoming_havdalah',
  parsha: 'sensor.jewish_calendar_parshat_hashavua',
  holiday: 'sensor.jewish_calendar_holiday',
  hebrewDate: 'sensor.jewish_calendar_date',
  sun: 'sun.sun',
};

export const SIZE_PRESETS = {
  tiny: {
    cardSize: 1,
    padding: '8px 12px',
    minHeight: '0',
    titleSize: '1em',
    subtitleSize: '0.7em',
    countdownSize: '1.1em',
    cdLabelSize: '0.6em',
    heroSize: '1em',
    heroMargin: '0',
    candleGap: '8px',
    candleH: '28px',
    flameW: '6px', flameH: '10px', fwW: '8px', fwH: '12px',
    glowSize: '10px', glowOff: '-2px',
    stickW: '3px', stickH: '16px',
    showRing: false, showTimes: false, showDate: false, showStars: false,
    showIcon: false, showSubtitle: false, showCdLabel: false,
    horizontal: true,
    timesSize: '0.7em', dateSize: '0.65em',
    ringSize: 60, ringStroke: 3, ringPctSize: '0.9em', ringLblSize: '0.5em',
    ringMargin: '4px 0 2px',
    timesGap: '14px', timesMargin: '4px',
  },
  compact: {
    cardSize: 2,
    padding: '10px 12px 8px',
    minHeight: '80px',
    titleSize: '1.1em',
    subtitleSize: '0.75em',
    countdownSize: '1.3em',
    cdLabelSize: '0.65em',
    heroSize: '1.4em',
    heroMargin: '2px',
    candleGap: '12px',
    candleH: '36px',
    flameW: '7px', flameH: '13px', fwW: '9px', fwH: '15px',
    glowSize: '14px', glowOff: '-2px',
    stickW: '4px', stickH: '20px',
    showRing: false, showTimes: false, showDate: false, showStars: true,
    showIcon: true, showSubtitle: false, showCdLabel: true,
    horizontal: false, twoCol: true, twoColGap: '10px',
    timesSize: '0.75em', dateSize: '0.7em',
    ringSize: 70, ringStroke: 3, ringPctSize: '1em', ringLblSize: '0.5em',
    ringMargin: '6px 0 2px',
    timesGap: '16px', timesMargin: '6px',
  },
  small: {
    cardSize: 3,
    padding: '14px 12px 12px',
    minHeight: '120px',
    titleSize: '1.3em',
    subtitleSize: '0.8em',
    countdownSize: '1.6em',
    cdLabelSize: '0.7em',
    heroSize: '1.8em',
    heroMargin: '4px',
    candleGap: '16px',
    candleH: '50px',
    flameW: '10px', flameH: '18px', fwW: '12px', fwH: '20px',
    glowSize: '18px', glowOff: '-3px',
    stickW: '5px', stickH: '28px',
    showRing: true, showTimes: false, showDate: false, showStars: true,
    showIcon: true, showSubtitle: true, showCdLabel: true,
    horizontal: false, twoCol: true, twoColGap: '14px',
    timesSize: '0.8em', dateSize: '0.75em',
    ringSize: 80, ringStroke: 4, ringPctSize: '1.1em', ringLblSize: '0.55em',
    ringMargin: '10px 0 4px',
    timesGap: '20px', timesMargin: '8px',
  },
  medium: {
    cardSize: 5,
    padding: '20px 16px 18px',
    minHeight: '200px',
    titleSize: '1.8em',
    subtitleSize: '1em',
    countdownSize: '2.1em',
    cdLabelSize: '0.8em',
    heroSize: '2.5em',
    heroMargin: '8px',
    candleGap: '22px',
    candleH: '70px',
    flameW: '13px', flameH: '22px', fwW: '15px', fwH: '26px',
    glowSize: '24px', glowOff: '-4px',
    stickW: '6px', stickH: '38px',
    showRing: true, showTimes: true, showDate: true, showStars: true,
    showIcon: true, showSubtitle: true, showCdLabel: true,
    horizontal: false,
    timesSize: '0.85em', dateSize: '0.8em',
    ringSize: 100, ringStroke: 5, ringPctSize: '1.4em', ringLblSize: '0.6em',
    ringMargin: '14px 0 6px',
    timesGap: '30px', timesMargin: '12px',
  },
  large: {
    cardSize: 7,
    padding: '28px 20px 24px',
    minHeight: '280px',
    titleSize: '2.2em',
    subtitleSize: '1.15em',
    countdownSize: '2.6em',
    cdLabelSize: '0.85em',
    heroSize: '3.2em',
    heroMargin: '10px',
    candleGap: '28px',
    candleH: '90px',
    flameW: '16px', flameH: '28px', fwW: '18px', fwH: '32px',
    glowSize: '30px', glowOff: '-6px',
    stickW: '7px', stickH: '48px',
    showRing: true, showTimes: true, showDate: true, showStars: true,
    showIcon: true, showSubtitle: true, showCdLabel: true,
    horizontal: false,
    timesSize: '0.95em', dateSize: '0.85em',
    ringSize: 130, ringStroke: 6, ringPctSize: '1.7em', ringLblSize: '0.7em',
    ringMargin: '20px 0 10px',
    timesGap: '40px', timesMargin: '18px',
  }
};

export const CANDLE_SIZES = {
  large:   { svgW: 80, svgH: 200, bodyW: 22, bodyMaxH: 110, pad: 20, flameH: 28, flameW: 12, wickH: 10, poolRxBase: 18, poolGrow: 6, bulge: 3.5, hlW: 3 },
  medium:  { svgW: 60, svgH: 150, bodyW: 16, bodyMaxH: 75,  pad: 15, flameH: 22, flameW: 9,  wickH: 7,  poolRxBase: 13, poolGrow: 4, bulge: 2.5, hlW: 2.5 },
  small:   { svgW: 44, svgH: 100, bodyW: 12, bodyMaxH: 50,  pad: 10, flameH: 16, flameW: 7,  wickH: 5,  poolRxBase: 10, poolGrow: 3, bulge: 2,   hlW: 2 },
  compact: { svgW: 32, svgH: 70,  bodyW: 9,  bodyMaxH: 34,  pad: 8,  flameH: 12, flameW: 5,  wickH: 4,  poolRxBase: 7,  poolGrow: 2, bulge: 1.5, hlW: 1.5 },
  tiny:    { svgW: 22, svgH: 44,  bodyW: 6,  bodyMaxH: 20,  pad: 5,  flameH: 8,  flameW: 3.5, wickH: 3, poolRxBase: 5,  poolGrow: 1.5, bulge: 1, hlW: 1 },
};

export const DEFAULT_CONFIG = {
  size: 'large',
  preview: 'off',
};

export const PREVIEW_DATA = {
  pre_shabbat: {
    issur: false,
    motzei: false,
    preShabbat: true,
    holiday: '',
    progress: 0,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: 'Vayakhel-Pekudei',
    countdown: '14m',
    countdownLabel: 'Until Shabbat',
    targetTimeLocal: 'Friday 7:42 PM',
    candleLighting: '7:24 PM',
    havdalah: '8:20 PM',
    hebrewDate: '19 Adar 5786',
  },
  shabbat_early: {
    issur: true,
    motzei: false,
    holiday: '',
    progress: 5,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: 'Vayakhel-Pekudei',
    countdown: '24h 15m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Saturday 8:20 PM',
    candleLighting: '7:24 PM',
    havdalah: '8:20 PM',
    hebrewDate: '19 Adar 5786',
  },
  shabbat_mid: {
    issur: true,
    motzei: false,
    holiday: '',
    progress: 52,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: 'Vayakhel-Pekudei',
    countdown: '11h 45m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Saturday 8:20 PM',
    candleLighting: '7:24 PM',
    havdalah: '8:20 PM',
    hebrewDate: '20 Adar 5786',
  },
  shabbat_late: {
    issur: true,
    motzei: false,
    holiday: '',
    progress: 92,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: 'Vayakhel-Pekudei',
    countdown: '1h 58m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Saturday 8:20 PM',
    candleLighting: '7:24 PM',
    havdalah: '8:20 PM',
    hebrewDate: '20 Adar 5786',
  },
  motzei: {
    issur: false,
    motzei: true,
    holiday: '',
    progress: 0,
    statusText: '\u05E9\u05D1\u05D5\u05E2 \u05D8\u05D5\u05D1',
    statusSubtitle: 'Vayakhel-Pekudei',
    countdown: '5d 21h',
    countdownLabel: 'Until Candle Lighting',
    targetTimeLocal: 'Friday 7:20 PM',
    candleLighting: '7:20 PM',
    havdalah: '8:16 PM',
    hebrewDate: '20 Adar 5786',
  },
  yom_tov: {
    issur: true,
    motzei: false,
    holiday: 'Pesach',
    progress: 35,
    statusText: '\u05D7\u05D2 \u05E9\u05DE\u05D7',
    statusSubtitle: 'Pesach',
    countdown: '16h 30m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Monday 8:10 PM',
    candleLighting: '7:15 PM',
    havdalah: '8:10 PM',
    hebrewDate: '15 Nisan 5786',
  },
};
