export const VERSION = '1.1.0-dev.3';

export const ENTITIES = {
  issurMelacha: 'binary_sensor.jewish_calendar_issur_melacha_in_effect',
  motzei: 'binary_sensor.jewish_calendar_motzei_shabbat_hag',
  candleLighting: 'sensor.jewish_calendar_upcoming_candle_lighting',
  havdalah: 'sensor.jewish_calendar_upcoming_havdalah',
  parsha: 'sensor.jewish_calendar_parshat_hashavua',
  holiday: 'sensor.jewish_calendar_holiday',
  hebrewDate: 'sensor.jewish_calendar_date',
  sun: 'sun.sun',
};

export const SIZE_PRESETS = {
  tiny: {
    cardSize: 1,
    padding: '8px 12px',
    minHeight: '0',
    titleSize: '1em',
    subtitleSize: '0.7em',
    countdownSize: '1.1em',
    cdLabelSize: '0.6em',
    heroSize: '1em',
    heroMargin: '0',
    candleGap: '8px',
    candleH: '28px',
    flameW: '6px', flameH: '10px', fwW: '8px', fwH: '12px',
    glowSize: '10px', glowOff: '-2px',
    stickW: '3px', stickH: '16px',
    showRing: false, showTimes: false, showDate: false, showStars: false,
    showIcon: false, showSubtitle: false, showCdLabel: false,
    horizontal: true,
    timesSize: '0.7em', dateSize: '0.65em',
    ringSize: 60, ringStroke: 3, ringPctSize: '0.9em', ringLblSize: '0.5em',
    ringMargin: '4px 0 2px',
    timesGap: '14px', timesMargin: '4px',
  },
  compact: {
    cardSize: 2,
    padding: '10px 12px 8px',
    minHeight: '80px',
    titleSize: '1.1em',
    subtitleSize: '0.75em',
    countdownSize: '1.3em',
    cdLabelSize: '0.65em',
    heroSize: '1.4em',
    heroMargin: '2px',
    candleGap: '12px',
    candleH: '36px',
    flameW: '7px', flameH: '13px', fwW: '9px', fwH: '15px',
    glowSize: '14px', glowOff: '-2px',
    stickW: '4px', stickH: '20px',
    showRing: false, showTimes: false, showDate: false, showStars: true,
    showIcon: true, showSubtitle: false, showCdLabel: true,
    horizontal: false, twoCol: true, twoColGap: '10px',
    timesSize: '0.75em', dateSize: '0.7em',
    ringSize: 70, ringStroke: 3, ringPctSize: '1em', ringLblSize: '0.5em',
    ringMargin: '6px 0 2px',
    timesGap: '16px', timesMargin: '6px',
  },
  small: {
    cardSize: 3,
    padding: '14px 12px 12px',
    minHeight: '120px',
    titleSize: '1.3em',
    subtitleSize: '0.8em',
    countdownSize: '1.6em',
    cdLabelSize: '0.7em',
    heroSize: '1.8em',
    heroMargin: '4px',
    candleGap: '16px',
    candleH: '50px',
    flameW: '10px', flameH: '18px', fwW: '12px', fwH: '20px',
    glowSize: '18px', glowOff: '-3px',
    stickW: '5px', stickH: '28px',
    showRing: true, showTimes: false, showDate: false, showStars: true,
    showIcon: true, showSubtitle: true, showCdLabel: true,
    horizontal: false, twoCol: true, twoColGap: '14px',
    timesSize: '0.8em', dateSize: '0.75em',
    ringSize: 80, ringStroke: 4, ringPctSize: '1.1em', ringLblSize: '0.55em',
    ringMargin: '10px 0 4px',
    timesGap: '20px', timesMargin: '8px',
  },
  medium: {
    cardSize: 5,
    padding: '20px 16px 18px',
    minHeight: '200px',
    titleSize: '1.8em',
    subtitleSize: '1em',
    countdownSize: '2.1em',
    cdLabelSize: '0.8em',
    heroSize: '2.5em',
    heroMargin: '8px',
    candleGap: '22px',
    candleH: '70px',
    flameW: '13px', flameH: '22px', fwW: '15px', fwH: '26px',
    glowSize: '24px', glowOff: '-4px',
    stickW: '6px', stickH: '38px',
    showRing: true, showTimes: true, showDate: true, showStars: true,
    showIcon: true, showSubtitle: true, showCdLabel: true,
    horizontal: false,
    timesSize: '0.85em', dateSize: '0.8em',
    ringSize: 100, ringStroke: 5, ringPctSize: '1.4em', ringLblSize: '0.6em',
    ringMargin: '14px 0 6px',
    timesGap: '30px', timesMargin: '12px',
  },
  large: {
    cardSize: 7,
    padding: '28px 20px 24px',
    minHeight: '280px',
    titleSize: '2.2em',
    subtitleSize: '1.15em',
    countdownSize: '2.6em',
    cdLabelSize: '0.85em',
    heroSize: '3.2em',
    heroMargin: '10px',
    candleGap: '28px',
    candleH: '90px',
    flameW: '16px', flameH: '28px', fwW: '18px', fwH: '32px',
    glowSize: '30px', glowOff: '-6px',
    stickW: '7px', stickH: '48px',
    showRing: true, showTimes: true, showDate: true, showStars: true,
    showIcon: true, showSubtitle: true, showCdLabel: true,
    horizontal: false,
    timesSize: '0.95em', dateSize: '0.85em',
    ringSize: 130, ringStroke: 6, ringPctSize: '1.7em', ringLblSize: '0.7em',
    ringMargin: '20px 0 10px',
    timesGap: '40px', timesMargin: '18px',
  }
};

export const CANDLE_SIZES = {
  large:   { svgW: 80, svgH: 200, bodyW: 22, bodyMaxH: 110, pad: 20, flameH: 28, flameW: 12, wickH: 10, poolRxBase: 18, poolGrow: 6, bulge: 3.5, hlW: 3 },
  medium:  { svgW: 60, svgH: 150, bodyW: 16, bodyMaxH: 75,  pad: 15, flameH: 22, flameW: 9,  wickH: 7,  poolRxBase: 13, poolGrow: 4, bulge: 2.5, hlW: 2.5 },
  small:   { svgW: 44, svgH: 100, bodyW: 12, bodyMaxH: 50,  pad: 10, flameH: 16, flameW: 7,  wickH: 5,  poolRxBase: 10, poolGrow: 3, bulge: 2,   hlW: 2 },
  compact: { svgW: 32, svgH: 70,  bodyW: 9,  bodyMaxH: 34,  pad: 8,  flameH: 12, flameW: 5,  wickH: 4,  poolRxBase: 7,  poolGrow: 2, bulge: 1.5, hlW: 1.5 },
  tiny:    { svgW: 22, svgH: 44,  bodyW: 6,  bodyMaxH: 20,  pad: 5,  flameH: 8,  flameW: 3.5, wickH: 3, poolRxBase: 5,  poolGrow: 1.5, bulge: 1, hlW: 1 },
};

export const HOLIDAY_DAYS = [
  // Major Yom Tov
  { month: 'Tishrei', day: 1, name: 'Rosh Hashana I', category: 'major', festival: 'Rosh Hashana', sensorName: 'Rosh Hashana I' },
  { month: 'Tishrei', day: 2, name: 'Rosh Hashana II', category: 'major', festival: 'Rosh Hashana', sensorName: 'Rosh Hashana II', diasporaOnly: false },
  { month: 'Tishrei', day: 10, name: 'Yom Kippur', category: 'major', festival: null, sensorName: 'Yom Kippur' },
  { month: 'Tishrei', day: 15, name: 'Sukkot I', category: 'major', festival: 'Sukkot', sensorName: 'Sukkot' },
  { month: 'Tishrei', day: 16, name: 'Sukkot II', category: 'major', festival: 'Sukkot', sensorName: 'Sukkot II', diasporaOnly: true },
  { month: 'Tishrei', day: 22, name: 'Shmini Atzeret', category: 'major', festival: null, sensorName: 'Shmini Atzeret' },
  { month: 'Tishrei', day: 23, name: 'Simchat Torah', category: 'major', festival: null, sensorName: 'Simchat Torah', diasporaOnly: true },
  { month: 'Nisan', day: 15, name: 'Pesach I', category: 'major', festival: 'Pesach', sensorName: 'Pesach' },
  { month: 'Nisan', day: 16, name: 'Pesach II', category: 'major', festival: 'Pesach', sensorName: 'Pesach II', diasporaOnly: true },
  { month: 'Nisan', day: 21, name: 'Pesach VII', category: 'major', festival: 'Pesach', sensorName: 'Pesach VII' },
  { month: 'Nisan', day: 22, name: 'Pesach VIII', category: 'major', festival: 'Pesach', sensorName: 'Pesach VIII', diasporaOnly: true },
  { month: 'Sivan', day: 6, name: 'Shavuot', category: 'major', festival: 'Shavuot', sensorName: 'Shavuot' },
  { month: 'Sivan', day: 7, name: 'Shavuot II', category: 'major', festival: 'Shavuot', sensorName: 'Shavuot II', diasporaOnly: true },
  // Minor / Rabbinic
  { month: 'Kislev', day: 25, name: 'Chanukah I', category: 'minor', festival: 'Chanukah', sensorName: 'Chanukah' },
  { month: 'Kislev', day: 26, name: 'Chanukah II', category: 'minor', festival: 'Chanukah', sensorName: 'Chanukah' },
  { month: 'Kislev', day: 27, name: 'Chanukah III', category: 'minor', festival: 'Chanukah', sensorName: 'Chanukah' },
  { month: 'Kislev', day: 28, name: 'Chanukah IV', category: 'minor', festival: 'Chanukah', sensorName: 'Chanukah' },
  { month: 'Kislev', day: 29, name: 'Chanukah V', category: 'minor', festival: 'Chanukah', sensorName: 'Chanukah' },
  { month: 'Kislev', day: 30, name: 'Chanukah VI', category: 'minor', festival: 'Chanukah', sensorName: 'Chanukah' },
  { month: 'Tevet', day: 1, name: 'Chanukah VII', category: 'minor', festival: 'Chanukah', sensorName: 'Chanukah' },
  { month: 'Tevet', day: 2, name: 'Chanukah VIII', category: 'minor', festival: 'Chanukah', sensorName: 'Chanukah' },
  { month: 'Adar', day: 14, name: 'Purim', category: 'minor', festival: null, sensorName: 'Purim' },
  { month: 'Adar', day: 15, name: 'Shushan Purim', category: 'minor', festival: null, sensorName: 'Shushan Purim' },
  { month: 'Shvat', day: 15, name: "Tu B'Shvat", category: 'minor', festival: null, sensorName: "Tu B'Shvat" },
  { month: 'Iyyar', day: 18, name: "Lag B'Omer", category: 'minor', festival: null, sensorName: 'Lag BaOmer' },
  { month: 'Av', day: 15, name: "Tu B'Av", category: 'minor', festival: null, sensorName: "Tu B'Av" },
  // Fast days
  { month: 'Tishrei', day: 3, name: 'Tzom Gedaliah', category: 'fast', festival: null, sensorName: 'Tzom Gedaliah' },
  { month: 'Tevet', day: 10, name: "Asara B'Tevet", category: 'fast', festival: null, sensorName: "Asara B'Tevet" },
  { month: 'Adar', day: 13, name: "Ta'anit Esther", category: 'fast', festival: null, sensorName: "Ta'anit Esther" },
  { month: 'Tammuz', day: 17, name: 'Tzom Tammuz', category: 'fast', festival: null, sensorName: "Shiva Asar B'Tammuz" },
  { month: 'Av', day: 9, name: "Tish'a B'Av", category: 'fast', festival: null, sensorName: "Tish'a B'Av" },
];

export const FESTIVAL_PERIODS = [
  { name: 'Rosh Hashana', startMonth: 'Tishrei', startDay: 1, endMonth: 'Tishrei', endDay: 2 },
  { name: 'Sukkot', startMonth: 'Tishrei', startDay: 15, endMonth: 'Tishrei', endDay: 23, endDayIsrael: 22 },
  { name: 'Pesach', startMonth: 'Nisan', startDay: 15, endMonth: 'Nisan', endDay: 22, endDayIsrael: 21 },
  { name: 'Shavuot', startMonth: 'Sivan', startDay: 6, endMonth: 'Sivan', endDay: 7, endDayIsrael: 6 },
  { name: 'Chanukah', startMonth: 'Kislev', startDay: 25, endMonth: 'Tevet', endDay: 2 },
];

export const HOLIDAY_THEMES = {
  'Rosh Hashana': { gradient: 'linear-gradient(180deg, #1a1a4e 0%, #8B6914 50%, #DAA520 100%)', category: 'major', greeting: 'שנה טובה' },
  'Yom Kippur': { gradient: 'linear-gradient(180deg, #0a0a1a 0%, #1a1a2e 50%, #2d2d4a 100%)', category: 'major', greeting: 'גמר חתימה טובה' },
  'Sukkot': { gradient: 'linear-gradient(180deg, #1a3a1a 0%, #2d5a27 50%, #4a8c3f 100%)', category: 'major', greeting: 'חג שמח' },
  'Shmini Atzeret': { gradient: 'linear-gradient(180deg, #1a1a4e 0%, #3d2066 50%, #6b3fa0 100%)', category: 'major', greeting: 'חג שמח' },
  'Simchat Torah': { gradient: 'linear-gradient(180deg, #1a1a4e 0%, #3d2066 50%, #6b3fa0 100%)', category: 'major', greeting: 'חג שמח' },
  'Pesach': { gradient: 'linear-gradient(180deg, #1a1a4e 0%, #2d1810 50%, #5c3a1e 100%)', category: 'major', greeting: 'חג שמח' },
  'Shavuot': { gradient: 'linear-gradient(180deg, #1a1a4e 0%, #4a3060 50%, #8b5e83 100%)', category: 'major', greeting: 'חג שמח' },
  'Chanukah': { gradient: 'linear-gradient(180deg, #0a1628 0%, #1a3a5c 50%, #2b6cb0 100%)', category: 'minor', greeting: 'חג שמח' },
  'Purim': { gradient: 'linear-gradient(180deg, #1a1a4e 0%, #4a1a5c 50%, #7b3fa0 100%)', category: 'minor', greeting: 'חג שמח' },
  'Shushan Purim': { gradient: 'linear-gradient(180deg, #1a1a4e 0%, #4a1a5c 50%, #7b3fa0 100%)', category: 'minor', greeting: 'חג שמח' },
  "Tu B'Shvat": { gradient: 'linear-gradient(180deg, #1a2a1a 0%, #3a5a2a 50%, #5a8a4a 100%)', category: 'minor', greeting: 'חג שמח' },
  'Lag BaOmer': { gradient: 'linear-gradient(180deg, #1a1a1a 0%, #4a2a1a 50%, #8a4a2a 100%)', category: 'minor', greeting: 'חג שמח' },
  "Tu B'Av": { gradient: 'linear-gradient(180deg, #1a1a4e 0%, #3d2b6b 50%, #7b4fa0 100%)', category: 'minor', greeting: 'חג שמח' },
  'Tzom Gedaliah': { gradient: 'linear-gradient(180deg, #1a1a1a 0%, #2d2d2d 50%, #4a4a4a 100%)', category: 'fast', greeting: '' },
  "Asara B'Tevet": { gradient: 'linear-gradient(180deg, #1a1a1a 0%, #2d2d2d 50%, #4a4a4a 100%)', category: 'fast', greeting: '' },
  "Ta'anit Esther": { gradient: 'linear-gradient(180deg, #1a1a1a 0%, #2d2d2d 50%, #4a4a4a 100%)', category: 'fast', greeting: '' },
  "Shiva Asar B'Tammuz": { gradient: 'linear-gradient(180deg, #1a1a1a 0%, #2d2d2d 50%, #4a4a4a 100%)', category: 'fast', greeting: '' },
  "Tish'a B'Av": { gradient: 'linear-gradient(180deg, #0a0a0a 0%, #1a1a1a 50%, #2d2d2d 100%)', category: 'fast', greeting: '' },
};

export const DEFAULT_CONFIG = {
  size: 'large',
  preview: 'off',
  diaspora: true,
  major_holiday_lead_days: 14,
  minor_holiday_lead_days: 5,
};

export const PREVIEW_DATA = {
  pre_shabbat: {
    issur: false,
    motzei: false,
    preShabbat: true,
    holiday: '',
    progress: 0,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: 'Vayakhel-Pekudei',
    countdown: '14m',
    countdownLabel: 'Until Shabbat',
    targetTimeLocal: 'Friday 7:42 PM',
    candleLighting: '7:24 PM',
    havdalah: '8:20 PM',
    hebrewDate: '19 Adar 5786',
  },
  shabbat_early: {
    issur: true,
    motzei: false,
    preShabbat: false,
    holiday: '',
    progress: 5,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: 'Vayakhel-Pekudei',
    countdown: '24h 15m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Saturday 8:20 PM',
    candleLighting: '7:24 PM',
    havdalah: '8:20 PM',
    hebrewDate: '19 Adar 5786',
  },
  shabbat_mid: {
    issur: true,
    motzei: false,
    preShabbat: false,
    holiday: '',
    progress: 52,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: 'Vayakhel-Pekudei',
    countdown: '11h 45m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Saturday 8:20 PM',
    candleLighting: '7:24 PM',
    havdalah: '8:20 PM',
    hebrewDate: '20 Adar 5786',
  },
  shabbat_late: {
    issur: true,
    motzei: false,
    preShabbat: false,
    holiday: '',
    progress: 92,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: 'Vayakhel-Pekudei',
    countdown: '1h 58m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Saturday 8:20 PM',
    candleLighting: '7:24 PM',
    havdalah: '8:20 PM',
    hebrewDate: '20 Adar 5786',
  },
  motzei: {
    issur: false,
    motzei: true,
    preShabbat: false,
    holiday: '',
    progress: 0,
    statusText: '\u05E9\u05D1\u05D5\u05E2 \u05D8\u05D5\u05D1',
    statusSubtitle: 'Vayakhel-Pekudei',
    countdown: '5d 21h',
    countdownLabel: 'Until Candle Lighting',
    targetTimeLocal: 'Friday 7:20 PM',
    candleLighting: '7:20 PM',
    havdalah: '8:16 PM',
    hebrewDate: '20 Adar 5786',
  },
  yom_tov: {
    issur: true,
    motzei: false,
    preShabbat: false,
    holiday: 'Pesach',
    progress: 35,
    statusText: '\u05D7\u05D2 \u05E9\u05DE\u05D7',
    statusSubtitle: 'Pesach',
    countdown: '16h 30m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Monday 8:10 PM',
    candleLighting: '7:15 PM',
    havdalah: '8:10 PM',
    hebrewDate: '15 Nisan 5786',
  },
  holiday_approaching: {
    issur: false,
    motzei: false,
    holiday: '',
    progress: 0,
    statusText: '\u05D7\u05D2 \u05E9\u05DE\u05D7',
    statusSubtitle: 'Pesach in 5 days',
    countdown: '5d 2h',
    countdownLabel: 'Until Pesach',
    targetTimeLocal: 'Thursday 7:15 PM',
    candleLighting: '7:15 PM',
    havdalah: '8:10 PM',
    hebrewDate: '10 Nisan 5786',
    nextHoliday: { name: 'Pesach I', category: 'major', festival: 'Pesach', sensorName: 'Pesach', daysUntil: 5 },
    holidayMode: 'approaching',
  },
  holiday_shabbat_merge: {
    issur: true,
    motzei: false,
    holiday: '',
    progress: 25,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: 'Tzav',
    countdown: '20h 15m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Saturday 8:10 PM',
    candleLighting: '7:15 PM',
    havdalah: '8:10 PM',
    hebrewDate: '12 Nisan 5786',
    nextHoliday: { name: 'Pesach I', category: 'major', festival: 'Pesach', sensorName: 'Pesach', daysUntil: 3 },
    holidayMode: 'shabbat_merge',
  },
  holiday_active: {
    issur: true,
    motzei: false,
    holiday: 'Pesach',
    progress: 35,
    statusText: '\u05D7\u05D2 \u05E9\u05DE\u05D7',
    statusSubtitle: 'Pesach',
    countdown: '16h 30m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Thursday 8:10 PM',
    candleLighting: '7:15 PM',
    havdalah: '8:10 PM',
    hebrewDate: '15 Nisan 5786',
    nextHoliday: { name: 'Pesach I', category: 'major', festival: 'Pesach', sensorName: 'Pesach', daysUntil: 0 },
    holidayMode: 'active',
  },
  holiday_shabbat_overlap: {
    issur: true,
    motzei: false,
    holiday: 'Pesach',
    progress: 40,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: 'Shabbat Chol HaMoed Pesach',
    countdown: '14h 45m',
    countdownLabel: 'Until Havdalah',
    targetTimeLocal: 'Saturday 8:10 PM',
    candleLighting: '7:15 PM',
    havdalah: '8:10 PM',
    hebrewDate: '16 Nisan 5786',
    nextHoliday: { name: 'Pesach I', category: 'major', festival: 'Pesach', sensorName: 'Pesach', daysUntil: 0 },
    holidayMode: 'shabbat_overlap',
  },
  fast_approaching: {
    issur: false,
    motzei: false,
    holiday: '',
    progress: 0,
    statusText: '\u05E9\u05D1\u05EA \u05E9\u05DC\u05D5\u05DD',
    statusSubtitle: '',
    countdown: '3d 5h',
    countdownLabel: 'Until Tzom Gedaliah',
    targetTimeLocal: 'Wednesday 5:30 AM',
    candleLighting: '7:00 PM',
    havdalah: '7:55 PM',
    hebrewDate: '1 Tishrei 5787',
    nextHoliday: { name: 'Tzom Gedaliah', category: 'fast', festival: null, sensorName: 'Tzom Gedaliah', daysUntil: 3 },
    holidayMode: 'approaching',
  },
  chanukah: {
    issur: false,
    motzei: false,
    holiday: 'Chanukah',
    progress: 0,
    statusText: '\u05D7\u05D2 \u05E9\u05DE\u05D7',
    statusSubtitle: 'Chanukah',
    countdown: '5d 16h',
    countdownLabel: 'Until Candle Lighting',
    targetTimeLocal: 'Friday 4:15 PM',
    candleLighting: '4:15 PM',
    havdalah: '5:20 PM',
    hebrewDate: '27 Kislev 5787',
    nextHoliday: { name: 'Chanukah', category: 'minor', festival: 'Chanukah', sensorName: 'Chanukah', daysUntil: 0 },
    holidayMode: 'active',
  },
};
